spring:
  cache:
    type: caffeine
    cache-names: files
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=86400s
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: ${PG_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: 123456

campaign:
  activation:
    cron: 0 * * * * ?

stripe:
  secret:
    key: ${STRIPE_SECRET_KEY}

minio:
  url: http://${MINIO_PRIVATE_HOST}:${MINIO_PRIVATE_PORT}
  access-key: ${MINIO_ROOT_USER}
  secret-key: ${MINIO_ROOT_PASSWORD}
  bucket-name: bird-bucket
