spring:
  cache:
    type: caffeine
    cache-names: files
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=86400s
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

  datasource:
    url: jdbc:postgresql://localhost:5432/my_database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: 123456

campaign:
  activation:
    cron: 0 * * * * ?
